FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 65421
EXPOSE 44332

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY WAW/WAW.csproj WAW/
RUN dotnet restore WAW/WAW.csproj
COPY . .
WORKDIR /src/WAW
RUN dotnet build WAW.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish WAW.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WAW.dll"]
